Récup_M1MIAGEApp_BDD_Dauphine
marcellinodour/MIDO-SVG pull request #10
Opened 2020-04-30 18:54 UTC by camillelanglois3

-Création classe RofDatabase (qui aura pour objectif à long terme de remplacer la classe Database) et test unitaire associé 
-Modification des classes DataRecuperator et ObjectTransformer 
-Modification du POM

2020-05-01 18:15 UTC, oliviercailloux requested changes
Il faut faire de RofDatabase un objet immuable : initialisé et puis plus modifié. Cela rendra votre programme plus clair dans son ensemble. Utilisez un pattern Builder pour ce faire. Cf. BP Local design.

RofDb utilise le DataRecuperator, et je ne crois pas que ce soit la meilleure façon de faire, car cela lie RofDb (et donc probablement toute votre application) au DataRecuperator. Il faut au contraire pouvoir l’utiliser avec d’autres modes de récupération des données (par exemple pour les tests unitaires). Donc, inverser la responsabiilité : c’est l’utilisateur de RofDb qui devrait lui fournir les données brutes (récupérées depuis DataRecuperator ou autre).

De manière générale, il faut réfléchir à la conception de cet objet.

2020-05-01 18:15 UTC, oliviercailloux commented on src/main/java/com/github/cocolollipop/mido_svg/database/DataRecuperator.java
> +	public static void getSubjects(String programID, Formation formation, List<Subject> subjects) throws StandardException {
Il est nettement plus clair de faire renvoyer à la méthode ce qu’elle est censée retourner. Il faut éviter de modifier des paramètres reçus (sauf cas où particulier).

2020-05-01 18:15 UTC, oliviercailloux commented on src/main/java/com/github/cocolollipop/mido_svg/database/ObjectTransformer.java
> +		Querier querier=new Querier();
BP FORMAT SVP

2020-05-01 18:15 UTC, oliviercailloux commented on src/main/java/com/github/cocolollipop/mido_svg/database/ObjectTransformer.java
> +		Person person = querier.getPerson(course.getManagingTeacher().getValue());
Comme je l’ai indiqué en UML, la séparation des responsabilités entre DataRecuperator et ObjectTransformer n’est pas claire : comme on voit ici, l’ObjectTransformer récupère lui aussi des données. Je maintiens donc ma recommandation : regrouper les deux aspects en une seule classe.

Libre à vous de ne pas trouver cette suggestion pertinente (il est possible que des subtilités m’aient échappées), mais je m’attends à ce que vous en discutiez, si c’est le cas.

2020-05-01 18:15 UTC, oliviercailloux commented on src/main/java/com/github/cocolollipop/mido_svg/database/RofDatabase.java
> +	//contructor
Évitez les commentaires inutiles SVP.

2020-05-01 18:15 UTC, oliviercailloux commented on src/main/java/com/github/cocolollipop/mido_svg/database/RofDatabase.java
> +		this.settings=new Settings(true, true, true, true, true, true, true, "A4");
Appliquez SVP BP Eclipse warnings.

2020-05-01 18:15 UTC, oliviercailloux commented on src/main/java/com/github/cocolollipop/mido_svg/database/RofDatabase.java
> +	//getter and setter
Format inapproprié et commentaire fragile (deviendra incorrect si on réordonne les méthodes) en plus d’être inutile ; à supprimer.

2020-05-01 18:15 UTC, oliviercailloux commented on src/main/java/com/github/cocolollipop/mido_svg/database/RofDatabase.java
> +	public void setPaper(Paper paper) {
Appliquez SVP BP null.

2020-05-01 18:15 UTC, oliviercailloux commented on src/main/java/com/github/cocolollipop/mido_svg/database/RofDatabase.java
> +	private List<Formation> formations;
Je soupçonne que cette liste de formations soit inutile, vu qu’elle est je suppose destinée à contenir les mêmes formations que celles dans la map. Conservez l’une ou l’autre, mais pas les deux.

2020-05-01 18:15 UTC, oliviercailloux commented on src/main/java/com/github/cocolollipop/mido_svg/database/RofDatabase.java
> +	private Map<String, Formation> formationsMap;
Que représentent ces `String` utilisés comme clés ? Comment l’utilisateur de la classe saura-t-il quelle clé utiliser pour trouver la formation souhaitée ?

2020-05-01 18:15 UTC, oliviercailloux commented on src/main/java/com/github/cocolollipop/mido_svg/database/RofDatabase.java
> +	private void FillSubjectListInFormation() {
minuscule

2020-05-01 18:15 UTC, oliviercailloux commented on src/main/java/com/github/cocolollipop/mido_svg/database/RofDatabase.java
> +		(formationsMap.get("M1MIAGEApp")).fillsubjectList(subjects);
Ceci échouera si `formationsMap` est `null`, il faut donc que le contrat le prévoie (implicitement ou explicitement) et agisse en fonction quand la précondition est non satisfaite.

2020-05-01 18:17 UTC, oliviercailloux requested changes

2020-05-01 18:17 UTC, oliviercailloux commented on src/test/java/com/github/cocolollipop/mido_svg/model/ObjectTransformerTest.java
> -class ObjectTransformerTest {
Pourquoi avoir effacé ces tests ? Ils me semblaient utiles. (Même chose pour `DataRecuperatorTest`.)

2020-05-02 13:46 UTC, marcellinodour commented on src/main/java/com/github/cocolollipop/mido_svg/database/DataRecuperator.java
> +	public static void getSubjects(String programID, Formation formation, List<Subject> subjects) throws StandardException {
Modification effectué, de part la fusion de la classe `DataRecuperator`et `RofDatabase`.
En effet, nous avons repensé au fonctionnement de la méthode, appelé maintenant `fetchSubject`.

2020-05-02 13:47 UTC, marcellinodour commented on src/main/java/com/github/cocolollipop/mido_svg/database/ObjectTransformer.java
> +		Querier querier=new Querier();
Modification effectuée.

2020-05-02 13:48 UTC, marcellinodour commented on src/main/java/com/github/cocolollipop/mido_svg/database/ObjectTransformer.java
> +		Person person = querier.getPerson(course.getManagingTeacher().getValue());
Modification effectuée.
Nous avons bien pris en compte votre suggestion et nous avons tout réunis dans la classe `RofdDatabase`. Cela nous semble effectivement plus pertinent.

2020-05-02 13:48 UTC, marcellinodour commented on src/main/java/com/github/cocolollipop/mido_svg/database/RofDatabase.java
> +	//contructor
Modification effectuée.

2020-05-02 13:50 UTC, marcellinodour commented on src/main/java/com/github/cocolollipop/mido_svg/database/RofDatabase.java
> +		this.settings=new Settings(true, true, true, true, true, true, true, "A4");
Modification effectuée.
Bien qu'ayant paramétré les préférences Eclipses selon vos recommandations, nous n'avons cependant pas de warning pour ce type mauvaise pratique. Que devons-nous faire ?

2020-05-02 13:50 UTC, marcellinodour commented on src/main/java/com/github/cocolollipop/mido_svg/database/RofDatabase.java
> +	//getter and setter
Modification effectuée.

2020-05-02 13:51 UTC, marcellinodour commented on src/main/java/com/github/cocolollipop/mido_svg/database/RofDatabase.java
> +	public void setPaper(Paper paper) {
Modification effectuée.
La méthode a été supprimé car l'attribut `paper` n'est pas utilisé. (redondant avec l'attribut `settings` qui admet déjà l'objet `paper`.

2020-05-02 13:52 UTC, marcellinodour commented on src/main/java/com/github/cocolollipop/mido_svg/database/RofDatabase.java
> +	private List<Formation> formations;
Modification effectuée.
Nous avons bien supprimé `formationsMap` qui nous semble effectivement inutile

2020-05-02 13:52 UTC, marcellinodour commented on src/main/java/com/github/cocolollipop/mido_svg/database/RofDatabase.java
> +	private Map<String, Formation> formationsMap;
Modification effectuée.

2020-05-02 13:53 UTC, marcellinodour commented on src/main/java/com/github/cocolollipop/mido_svg/database/RofDatabase.java
> +	private void FillSubjectListInFormation() {
Modification effectuée.

2020-05-02 13:54 UTC, marcellinodour commented on src/main/java/com/github/cocolollipop/mido_svg/database/RofDatabase.java
> +		(formationsMap.get("M1MIAGEApp")).fillsubjectList(subjects);
Modification effectuée.
Après suppression de l'attribut `formationsMap` cette méthode est obsolète.

2020-05-02 14:02 UTC, marcellinodour commented on src/test/java/com/github/cocolollipop/mido_svg/model/ObjectTransformerTest.java
> -class ObjectTransformerTest {
Effectivement, nous avons supprimer les tests `ObjectTransformerTest` et `DataRecuperatorTest`.

Cette action a été motivé par :
- le fait que notre test _semble_ couvrir l'ensemble des tests précédemment effacés
- les méthodes ont changé
- les tests n'étaient correctement rédigés

De plus, nous avons prévus de supprimer les classes (choses faite à ce jour).
Nous (ou les équipes suivantes) prévoyons d'implémenter des tests un peu plus exhaustifs après résolution du problème https://github.com/marcellinodour/MIDO-SVG/issues/11 (en cours de traitement).

Qu'en pensez-vous ?

2020-05-02 14:04 UTC, marcellinodour commented
Modifications effectuées, 
Est-ce ok pour vous ?

2020-05-05 18:37 UTC, oliviercailloux commented on src/main/java/com/github/cocolollipop/mido_svg/database/RofDatabase.java
> +		this.settings=new Settings(true, true, true, true, true, true, true, "A4");
Je ne sais plus ce que j’avais en tête !

2020-05-05 19:10 UTC, oliviercailloux requested changes
Il faudra à terme distinguer la récupération des données (fetch*) et l’aggrégation des données en une seule instance, qui ne me parait pas claire en l’état. FUTURE

2020-05-05 19:10 UTC, oliviercailloux commented on src/main/java/com/github/cocolollipop/mido_svg/database/RofDatabase.java
> +		this.settings = new Settings(true, true, true, true, true, true, true, "A4");
Ceci me semble sans rapport avec Rof.

2020-05-05 19:10 UTC, oliviercailloux commented on src/main/java/com/github/cocolollipop/mido_svg/database/RofDatabase.java
> +	private void setTeachers(ImmutableMap<String, Teacher> teachersList) {
Cette méthode privée d’une ligne ne sert à rien, autant mettre le code contenu directement là on on appellerait cette méthode, cela clarifie.

2020-05-05 19:10 UTC, oliviercailloux commented on src/main/java/com/github/cocolollipop/mido_svg/database/RofDatabase.java
> +	public List<Subject> getSubjects() {
Lisez SVP BP Local design, return types.

2020-05-05 19:10 UTC, oliviercailloux commented on src/main/java/com/github/cocolollipop/mido_svg/database/RofDatabase.java
> +	private static Subject createSubject(Course course, Formation formation) throws StandardException {
Évitez ces `StandardException` qui vont se propager partout ; appliquez BP Exception pour changer l’exception (IllState conviendrait ici).

2020-05-05 20:51 UTC, marcellinodour commented on src/main/java/com/github/cocolollipop/mido_svg/database/RofDatabase.java
> +		this.settings = new Settings(true, true, true, true, true, true, true, "A4");
Modification effectuée.

2020-05-05 20:51 UTC, marcellinodour commented on src/main/java/com/github/cocolollipop/mido_svg/database/RofDatabase.java
> +	private void setTeachers(ImmutableMap<String, Teacher> teachersList) {
Modification effectuée.

2020-05-05 20:51 UTC, marcellinodour commented on src/main/java/com/github/cocolollipop/mido_svg/database/RofDatabase.java
> +	public List<Subject> getSubjects() {
Modification effectuée.

2020-05-05 20:55 UTC, marcellinodour commented on src/main/java/com/github/cocolollipop/mido_svg/database/RofDatabase.java
> +	private static Subject createSubject(Course course, Formation formation) throws StandardException {
Modification effectuée.
Nous avons cependant émis des réserves sur la méthode `CreateSubject`.
A la récupération des `ManagingTeacher` nous ne savons pas si dans le cas de figure où le cours admet comme valeur `null` à ce dernier, est-ce un réellement un bug (auquelle cas un throw `IllegalStateException` est nécessaire ou un comportement normal.
Des données semblent manquer à ROF sur ce point.
cf : Issue https://github.com/marcellinodour/MIDO-SVG/issues/12

2020-05-06 12:48 UTC, oliviercailloux requested changes

2020-05-06 12:48 UTC, oliviercailloux commented on src/main/java/com/github/cocolollipop/mido_svg/database/RofDatabase.java
> +	private void setTeachers() {
Je préférais l’approche précédente, avec `fetch*`, qui est réutilisable plus facilement pour faire autre chose et est clair. Il fallait simplement effacer `set*`.

2020-05-06 12:48 UTC, oliviercailloux commented on src/main/java/com/github/cocolollipop/mido_svg/database/RofDatabase.java
> +	private void setSubjects() throws Exception {
Il ne faut toujours pas envoyer `Exception`, mais appliquer BP Exception pour transformer l’exception, cf. remarque précédente.

2020-05-06 12:48 UTC, oliviercailloux commented on src/main/java/com/github/cocolollipop/mido_svg/database/RofDatabase.java
> +			if (querier.getProgram(key) == null) {
Ceci n’est pas censé renvoyer `null`, dans la version de Plaquette mido, sauf erreur. Renvoyer `null` est une mauvaise pratique, comme indiqué dans BP null. Je vous prie de ne pas modifier ces classes, pour pouvoir utiliser une partie du code de plaquette-mido en dépendance à terme.

2020-05-28 23:08 UTC, oliviercailloux commented
Je ferme ceci, puisqu’on n’est plus à l’itération 2, en vous invitant à suivre les instructions de remise pour le projet.

2020-05-28 23:08 UTC, closed without merging