Dev svg2
marcellinodour/MIDO-SVG pull request #13
Opened 2020-05-02 15:56 UTC by camillelanglois3

Les modifications suivantes sont surtout une réappropriation du code :

Utilisation du grade plutôt que de faire une recherche de caractère dans le libellé
Remplacement des IF successifs par des boucles
Création de la methode countSubjects()
Récupération du nombre de max de sujets par grade à partir d'une de ces boucles
--> le but est de se servir du nombre max de sujets par grade pour construire un Offset Y adapté au grade et ainsi limiter les chevauchements verticaux.

2020-05-03 10:09 UTC, oliviercailloux requested changes

2020-05-03 10:09 UTC, oliviercailloux commented on src/main/java/com/github/cocolollipop/mido_svg/svg_generator/ResponsiveSVG.java
> +import sun.font.FontDesignMetrics;
Il est déconseillé de dépendre de packages `sun.*`, car leur inclusion dans la JDK n’est pas garantie. Voyez SVP si vous pouvez vous en passer.

2020-05-03 10:09 UTC, oliviercailloux commented on src/main/java/com/github/cocolollipop/mido_svg/svg_generator/ResponsiveSVG.java
> +
SVP évitez ces nombreuses lignes vides (ici et ailleurs). Une ligne vide pour séparer suffit. Cela maintient les fichiers compacts, donc moins de défilement nécessaire et ça fait moins peur au lecteur. OPT

2020-05-03 10:09 UTC, oliviercailloux commented on src/main/java/com/github/cocolollipop/mido_svg/svg_generator/ResponsiveSVG.java
> +	public int countSubjects(Formation formation) {
Je doute que cette méthode vaille la peine de figurer ici. Chaque méthode augmente un peu la complexité de votre API (et donc, par exemple, la difficulté pour un utilisateur de trouver la méthode qu’il veut quand il en cherche une autre ; la difficulté de trouver un bug quand on n’est pas sûr de quelle méthode est fautive ; etc.). Il faut par conséquent éviter d’inclure une méthode si elle peut se remplacer sans dommage par une ligne de code simple, ce qui est le cas ici (`formation.getSubjects().size()`, qui est à peine moins clair que `countSubjects(formation)`).

2020-05-03 10:09 UTC, oliviercailloux commented on src/main/java/com/github/cocolollipop/mido_svg/svg_generator/ResponsiveSVG.java
>  									 */
Appliquez je vous prie BP Style comments

2020-05-03 10:09 UTC, oliviercailloux commented on src/main/java/com/github/cocolollipop/mido_svg/svg_generator/ResponsiveSVG.java
> +		 * 		- the maximum number of subjects per grade--> each result is store on the array "maxsubj_per_grade"
Voyez BP FORMAT SVP

2020-05-03 10:09 UTC, oliviercailloux commented on src/main/java/com/github/cocolollipop/mido_svg/svg_generator/ResponsiveSVG.java
> +		int[] maxsubj_per_grade = new int[5];
Comme discuté par e-mail, je vous invite à utiliser plutôt des structures orientées objet telles que des `List`.

2020-05-03 10:09 UTC, oliviercailloux commented on src/main/java/com/github/cocolollipop/mido_svg/svg_generator/ResponsiveSVG.java
> +		}
C’est rarement une bonne idée de faire deux choses non intimement liées en même temps dans une boucle. Mieux vaut séparer en deux boucles, on perd très peu en performances et cela permet de se concentrer sur un problème à la fois (et aider le lecteur à suivre), de modifier le traitement séparément si on a une meilleure idée pour une des deux parties, etc.

Je vous invite donc à compter d’abord le nombre de formations par grade ; puis, dans une boucle distincte, vous occuper du nombre de sujets.

Ceci devrait vous aider à constater que vous pouvez faire nettement mieux, au moins pour le nombre de formations par grade (à savoir, une boucle simple au lieu d’une boucle imbriquée). Voyez aussi s’il est possible d’améliorer l’autre traitement.

2020-05-03 10:09 UTC, oliviercailloux commented on src/main/java/com/github/cocolollipop/mido_svg/svg_generator/ResponsiveSVG.java
> +		for (int i=0; i<=4; i++) {
Puisqu’il semble conceptuellement adéquat de trier les formations par grade, n’envisageriez-vous pas collectivement une structure appropriée pour ce faire, si elle n’existe pas déjà ? (FUTURE)

2020-05-04 19:45 UTC, brulej commented
Bonjour,

Je vais me passer du package sun mais je ne sais pas si mes autres solutions sont mieux. Utiliser la hauteur en dur dans le code ou créer un graphique uniquement pour pouvoir utiliser la methode getHeight() de java.awt.FontMetrics.

Je vais aussi utiliser des ArrayList mais je n'en comprends pas  l'utilité dans le cas présent. En effet, la taille de la liste n'a pas vocation à être modifiée. L'intérêt est-il seulement pédagogique afin de nous pousser à utiliser ce type d'objets ?

Cordialement,

Jérémie

2020-05-05 19:32 UTC, oliviercailloux requested changes

2020-05-05 19:32 UTC, oliviercailloux commented on src/main/java/com/github/cocolollipop/mido_svg/svg_generator/ResponsiveSVG.java
> +//import java.awt.FontMetrics;
Voyez SVP BP Style comments (et ne gérez pas vos imports manuellement !)

2020-05-05 19:32 UTC, oliviercailloux commented on src/main/java/com/github/cocolollipop/mido_svg/svg_generator/ResponsiveSVG.java
> +		ArrayList<Integer> nb_forma_per_grade2 = new ArrayList<Integer>();
Respectez SVP les conventions de nommage (BP style)

2020-05-05 19:32 UTC, oliviercailloux commented on src/main/java/com/github/cocolollipop/mido_svg/svg_generator/ResponsiveSVG.java
> +			int grade=f.getGrade();
Voyez SVP BP FORMATTING

2020-05-05 19:32 UTC, oliviercailloux commented on src/main/java/com/github/cocolollipop/mido_svg/svg_generator/ResponsiveSVG.java
> +		Iterator it = nb_forma_per_grade2.iterator();
Appliquez SVP BP Warnings Eclipse.

2020-05-05 19:32 UTC, oliviercailloux commented on src/main/java/com/github/cocolollipop/mido_svg/svg_generator/ResponsiveSVG.java
> +		while(it.hasNext()) {
Utiliser boucle for each de préférence.

2020-05-05 19:32 UTC, oliviercailloux commented on src/main/java/com/github/cocolollipop/mido_svg/svg_generator/ResponsiveSVG.java
> +		int offset_subject = 16 + 14;
Avez-vous essayé d’utiliser Graphics2D pour obtenir les "font metrics" ?

2020-05-05 19:36 UTC, oliviercailloux commented
> Je vais aussi utiliser des ArrayList mais je n'en comprends pas l'utilité dans le cas présent. En effet, la taille de la liste n'a pas vocation à être modifiée. L'intérêt est-il seulement pédagogique afin de nous pousser à utiliser ce type d'objets ?

Pédagogique et autre. Les collections sont plus capables et vous orientent vers des structures et approches plus générales (par exemple on se rend compte qu’on pourrait utiliser un Set au lieu d’une List, ou une Map). Ça ne se voit pas toujours au départ qu’on peut améliorer le code, mais petit à petit, les possibilités apparaissent. Certes, parfois pas, et dans ce cas la List restera telle quelle, ce n’est pas dommageable. (Les gains de performance des vecteurs primitifs sont très souvent absolument négligeables, et c’est le cas ici.)

2020-05-05 19:58 UTC, brulej commented on src/main/java/com/github/cocolollipop/mido_svg/svg_generator/ResponsiveSVG.java
> +		int offset_subject = 16 + 14;
Oui c'est ce qui est utilisé dans la classe DrawerSVGGen. C'est ce que j'avais voulu sous-entendre dans mon mail dimanche et le commentaire de cette méthode lundi soir.

2020-05-05 20:00 UTC, brulej commented on src/main/java/com/github/cocolollipop/mido_svg/svg_generator/ResponsiveSVG.java
> +//import java.awt.FontMetrics;
Je pensais avoir résolu le problème en mettant tous les commentaires au dessus. Visiblement je n'ai pas tout compris.

2020-05-05 21:19 UTC, brulej commented
Je comprends mieux comment le système de review marche... A coté de cette Pull Request j'avais travaillé sur la formule de l'offsetY mais j'attendais que celle-ci soit clôturée avant de la soumettre. Puis-je le faire sur une autre branche?

2020-05-06 13:13 UTC, oliviercailloux commented on src/main/java/com/github/cocolollipop/mido_svg/svg_generator/ResponsiveSVG.java
> +		int offset_subject = 16 + 14;
Importer plein de packages n’est pas un problème. Pour le reste, je ne sais pas, je n’ai pas regardé en détail, mais le problème principal est que je ne sais pas exactement ce que vous voulez faire.

2020-05-06 13:14 UTC, oliviercailloux commented
Voyez SVP les instructions et dites-moi précisément le passage concerné et ce qui n’est pas clair, si cela ne répond pas à votre question.

2020-05-06 13:16 UTC, oliviercailloux requested changes
Le problème de formating semble toujours présent. Avez-vous lu BP Style Formating ?

2020-06-08 14:47 UTC, closed without merging