Review it2 BDD + suppression users attributs
marcellinodour/MIDO-SVG pull request #18
Opened 2020-05-31 13:13 UTC by marcellinodour

PR non merge à l'it 2 en BDD.
Cette PR comprends :
- la reprise des tâches exécutés en it2 + une revue de l'equipe BDD it3
- suppression de l'attribut user de la BDD + les methodes associées, car non pertinent

2020-05-31 22:38 UTC, oliviercailloux requested changes
Voyez SVP pourquoi l’action GitHub ne s’est pas exécutée.

Retirez les changements que j’ai déjà reviewé dans une autre PR acceptée.

2020-06-01 08:40 UTC, marcellinodour reviewed
Previous change already viewed (cf PR #10)

2020-06-02 17:16 UTC, oliviercailloux requested changes
Résoudre les conflits SVP.

2020-06-08 14:42 UTC, marcellinodour commented
Clear après PR #22 , #23 , #24 , #25

2020-06-09 08:41 UTC, oliviercailloux requested changes
Je ne suis pas sûr de devoir reviewer cette PR, insistez si oui.

2020-06-10 09:53 UTC, closed without merging

2020-06-10 09:53 UTC, marcellinodour commented
ouverture d'un PR plus explicite