Evol COMPIL
marcellinodour/MIDO-SVG pull request #20
Opened 2020-06-02 08:09 UTC by marcellinodour

PR à la bonne compilation du projet sur Master. (cf : issue #16 )
Les changements apportés ont déjà été validé à l'itération précédente.

2020-06-02 17:49 UTC, oliviercailloux requested changes
Appliquez SEP (dans instructions) SVP. 21 fichiers changés, c’est trop pour moi.

2020-06-02 22:38 UTC, marcellinodour commented
Je crains être un peu perdu sur la notion de "Séparer les tâches". Nous concevons totalement que 21 fichiers modifiés ne peut être considéré comme une tâche et doit être par conséquent séparer (code SEP). Cependant, sauf erreur de ma part, ces modifications ont été validé au PR #10 mais n'a pas fait l'objet d'un _merge_. Ce PR a pour tâche de restaurer la compilation du projet en réponse à l'issue #16.
Que doit-on faire ?

2020-06-04 09:11 UTC, oliviercailloux commented
La PR #10 ne semble pas avoir été validée, d’après ce que je vois en suivant le lien. (Sinon, vous auriez effectivement déjà pu la fusionner et il n’y aurait pas lieu d’en introduire une nouvelle qui reprend les mêmes changements.)

De toute façon, je ne crois pas qu’il faille modifier 21 fichiers pour restaurer la compilation, et en particulier, en quoi ce problème de compilation serait lié à toutes ces modifications apparaissant en PR #10.

Je vous invite donc à introduire une PR qui propose des changements minimaux dans le seul but de permettre à nouveau de compiler le projet.

2020-06-04 09:11 UTC, oliviercailloux requested changes
Cf. commentaire ci-dessus.

2020-06-05 14:23 UTC, marcellinodour commented
Pourrions-nous échanger de vive-voix sur cette PR afin de vous exposer la nécessité de ces changements ? Je ne parviens pas à suivre la procédure à suivre en prenant en compte la demande SEP.

2020-06-07 07:32 UTC, oliviercailloux requested changes
J’ai répondu par e-mail il y a deux jours.

2020-06-08 13:52 UTC, closed without merging