Evol 4 compil 2
marcellinodour/MIDO-SVG pull request #23
Opened 2020-06-08 14:02 UTC by marcellinodour

Evol for compilation 2: (a faire après validation du PR #22 )
- fusion du package BDDQueries et model

2020-06-09 07:03 UTC, oliviercailloux requested changes
Je vous invite à relire les instructions SVP.

2020-06-10 05:50 UTC, marcellinodour commented
Après relecture des [Instruction](https://github.com/oliviercailloux/java-course/blob/master/Divers/Projets.adoc#instructions-de-livraison) nous n'avons pas saisie notre erreur. Pourriez-vous nous éclairer ? 
Nos excuses par avance

2020-06-10 09:01 UTC, oliviercailloux requested changes
Vous avez raison, ce n’était pas explicite dans les instructions (je l’ai ajouté à l’instant). Je vous prie à l’avenir de me demander une review uniquement lorsque vous êtes prêts pour une review (c-à-d, entre autres, que la tâche n’a pas de pré-requis à reviewer et fusionner avant).

Il semble que cette PR ne soit pas à jour : DataRecuperator par exemple a déjà été effacée précédemment, il me semble.

2020-06-10 09:49 UTC, marcellinodour commented
Merci pour votre retour.
Cette PR à pour objectif d'importer les classes `Queries` et `QueriesHelper` dans le package model afin d'unifier dans un package la récupération des datas et la future classe `ROFDatabase`

2020-06-10 12:48 UTC, oliviercailloux approved these changes
Je comprends l’objectif, mais le problème reste. Mais admettons, puisque effectivement les changements sont triviaux. Il faut cependant éviter que le problème se reproduise à l’avenir pour les PRs avec des changements non triviaux.

2020-06-11 07:48 UTC, merged