Dev svg it3
marcellinodour/MIDO-SVG pull request #26
Opened 2020-06-09 20:17 UTC by brulej

Bonjour,

Voici les modifications opérées par l'équipe SVG dans le cadre de cette pull request:

- Ajout d'une méthode controlSettings dans DrawerSVGGEN

- Modification du calcul de l’offsetY et de l’offsetX des formations dans ResponsiveSVG. Pour cela, nous avons créé des méthodes afin de calculer la taille utilisée par des objets en pixel. Dans le cas où il y aurait trop de cours et s'il y a chevauchement une exception est envoyée.

- Nous n'avons pas fait de tests unitaires car cela nous semble difficile de prédire la position d'une formation en fonction des autres.

- Actuellement, nos modifications ne sont pas forcément bien visibles car nous utilisons une petite base de données temporairement codée en dur. Une fois que nous serons connectés à ROFDatabase, ’il y aura plus de contenu et nous pourrons observer des modifications significatives (Nous nous en  sommes assurés en ajoutant temporairement beaucoup de cours dans la Database et simulant différents cas de figure).

L'équipe SM/PO

2020-06-10 08:06 UTC, marcellinodour commented
Check SMPO Done
Note : les tests SVG ont été mis temporairement en commentaire car nous constatons un écart de calcul entre l'environnement eclipse et le WF.

2020-06-11 08:44 UTC, oliviercailloux requested changes
Cette PR ne devrait pas intégrer les changements déjà acceptés (tel que effacement de DataRecuperator, un problème déjà relevé) ; ni des changements sans rapport (maven.yml). Je vous invite à respecter SEP.

Il faut faire passer les tests unitaires (et non pas les désactiver). Si je comprends bien, votre stratégie consiste à calculer la position exacte de chaque objet, il n’y a donc pas de bonne raison que cette position change d’un ordinateur à l’autre.

2020-06-11 08:44 UTC, oliviercailloux commented on src/main/java/com/github/cocolollipop/mido_svg/svg_generator/DrawerSVGGen.java
> +		if((posX>canvaX)||(posY>canvaY)) {
Appliquez FORMAT SVP.

2020-06-11 08:44 UTC, oliviercailloux commented on src/main/resources/images/mido-drawing.svg
>      ><g style="font-family:&apos;Serif&apos;;"
Veuillez respecter BP Ressources SVP. (Je sais que ce fichier était déjà présent, donc le problème pré-existe à votre PR, mais il faut quand-même le résoudre.)

2020-06-13 10:02 UTC, Raphda commented
En effet, la position ne changera pas d'un ordinateur à un autre.
Cependant, si nous fixons les positions en pixels en dur, dès que les données dans la BDD changeront (un nouveau cours, une formation supprimée etc) tous nos tests seront faux.
Et si nous calculons les positions en pixels, nous referons le même calcul que dans la méthode defineObjectPosition et les tests seront validés dans tous les cas, ce qui n'a pas beaucoup d'intérêt.
C'est pourquoi nous ne voyons pas comment faire nos tests unitaires. Qu'en pensez-vous ?

2020-06-13 10:47 UTC, Raphda commented
Pour les changements déjà acceptés, il s'agit d'un bug de GitHub. Nous avons exécuté votre méthode (changer la branche master par une autre puis la remettre) mais cela n'a toujours pas prit en compte le dernier commit de la branche master.

2020-06-13 10:49 UTC, Raphda commented on src/main/java/com/github/cocolollipop/mido_svg/svg_generator/DrawerSVGGen.java
> +		if((posX>canvaX)||(posY>canvaY)) {
Résolu

2020-06-13 10:51 UTC, Raphda commented on src/main/resources/images/mido-drawing.svg
>      ><g style="font-family:&apos;Serif&apos;;"
Nous avons modifié le code. Dorénavant, le SVG s'enregistre dans le même dossier que la où se trouve le projet. (Nous avons du mal à comprendre BP Ressources, cela vous convient-il ?)

2020-06-15 10:30 UTC, oliviercailloux requested changes
Comme discuté oralement aujourd’hui, il faut restaurer les tests et ajouter une tolérance de quelques pixels. À poursuivre dans nouvelle PR.

Veuillez appliquer le cours sur les chemins (files and flows) pour l’écriture des fichiers. FUTURE.

2020-06-15 10:30 UTC, oliviercailloux commented on src/main/java/com/github/cocolollipop/mido_svg/view/GUISVGGenerator.java
> +					File file = new File("../mido-drawing.svg");
Il convient d’utiliser la variable prévue à cet effet.

2020-06-15 10:30 UTC, oliviercailloux commented on src/main/java/com/github/cocolollipop/mido_svg/svg_generator/DrawerSVGGen.java
> +	public static final String DRAWING_SVG = "../mido-drawing.svg";
Écrivez plutôt dans le répertoire courant que dans le répertoire parent.

2020-06-22 11:35 UTC, oliviercailloux requested changes
Il me semble que les instructions projet n’ont pas été suivies. Voudriez-vous les relire et vérifier ?

2020-06-22 12:51 UTC, brulej commented
> Il me semble que les instructions projet n’ont pas été suivies. Voudriez-vous les relire et vérifier ?

.En demandant cette derniere request l'équipe SVG souhaitait attirer votre attention dans l'objectif de confirmer, la réévaluation de leur Itération. En effet, lors de notre dernière réunion teams, ces derniers ce sont rendus compte que la majeure partie de leur de travail n'avait pas été prise en compte (la classe Responsive-SVG).

Cela  vient d'un bug github concernant l'actualisation de la branch de référence. Vous n'avez pas pu voir l'étendue de leur à travail à cause du nombre trop important de fichiers modifiés dans cette PR.

Les modifications demandées  seront apportées dans le courant de la semaine par l'équipe concernée.

2020-06-23 11:58 UTC, oliviercailloux requested changes
Ok, je n’avais pas compris la raison de la demande de review.

2020-06-23 11:58 UTC, oliviercailloux commented on src/main/java/com/github/cocolollipop/mido_svg/svg_generator/ResponsiveSVG.java
> +	public Integer countMaxSubjects(List<Formation> list, String myYear) {
Appliquez BP null SVP.

2020-06-23 11:58 UTC, oliviercailloux commented on src/main/java/com/github/cocolollipop/mido_svg/svg_generator/ResponsiveSVG.java
> +	 * @param myYear the year for which we want to find the maximum number of subjects (L1, L2...)
Représenter une année par un entier serait plus clair, si possible.

2020-06-23 11:58 UTC, oliviercailloux commented on src/main/java/com/github/cocolollipop/mido_svg/svg_generator/ResponsiveSVG.java
> +				if (aFormation.getSubjects().size()>max) {
Cf. BP FORMAT, SVP.

2020-06-23 11:58 UTC, oliviercailloux commented on src/main/java/com/github/cocolollipop/mido_svg/svg_generator/ResponsiveSVG.java
> +	public Integer countMaxSubjects(List<Formation> list, String myYear) {
Je ne vois pas de raison de requérir une liste en entrée, plutôt qu’un Set ou un type plus général. Voir BP Local design, method parameters.

2020-06-23 11:58 UTC, oliviercailloux commented on src/main/java/com/github/cocolollipop/mido_svg/svg_generator/ResponsiveSVG.java
> +	public int calculateHeightOfSubjects(Integer nbOfSubjects) {
Même chose concernant types primitifs.

2020-06-23 11:58 UTC, oliviercailloux commented on src/main/java/com/github/cocolollipop/mido_svg/svg_generator/ResponsiveSVG.java
> +		int heightOfSubjects = (nbOfSubjects+1) * height + (nbOfSubjects+2) * 14 ;
Si qqn change 14 à un autre endroit, il n’y a aucune chance qu’il pense également à changer le 14 ici. Il faut lier ces valeurs, par exemple par le biais d’une constante.

2020-06-23 11:58 UTC, oliviercailloux commented on src/main/java/com/github/cocolollipop/mido_svg/svg_generator/ResponsiveSVG.java
> +		return max;
Ceci renvoie −1 si la liste est vide. Ce n’est sûrement pas ce qu’on veut.

2020-06-23 11:58 UTC, oliviercailloux commented on src/main/java/com/github/cocolollipop/mido_svg/svg_generator/ResponsiveSVG.java
> +		int formationBlock = 25+heightOfResponsibleName;
Même rmq.

Appliquez SVP BP Style.

2020-06-23 11:58 UTC, oliviercailloux commented on src/main/java/com/github/cocolollipop/mido_svg/svg_generator/ResponsiveSVG.java
>  		if (nbL3 != 0) {
Il serait bien plus clair de factoriser ce code (BP Local design). FUTURE.

2020-06-28 12:08 UTC, brulej commented
l'it3 est cloturée

2020-06-28 12:08 UTC, closed without merging