BDD it 3 : Ajout méthode getOrgUnit
marcellinodour/MIDO-SVG pull request #27
Opened 2020-06-10 09:56 UTC by marcellinodour

La récupération du département s’est faite sur deux étapes:
- Ajout des classes getOrgUnit et getOrgUnits dans Querier  
- à  partir de la clé correspondant au département MIDO dans refRof/root/OrgUnit on récupère le département

La récupération des formations ne pouvait se faire en cascade à partir du département. En effet, comme renseigné dans le diagramme de classe ROFDataBase, il n’existe pas de lien entre OrgUnit et Programs ou Mentions. Par conséquent, nous avons cherché les clés correspondant aux formations MIDO dans Rof et que nous avons utilisé ensuite pour récupérer les Mentions et convertir en Licence ou Master selon le niveau d’étude. Il existe d’ailleurs des doublons qu’il faut gérer.

La récupération des cours s’est faite à partir des programmes. En effet, chaque program pointe vers une liste de program (dans refProgram) et chaque Program  dans cette liste pointe vers une autre liste de Program et ainsi de suite. Quand on arrive aux niveaux les plus fins refProgram est vide et refCourse contient tous les cours correspondant aux Program(s) père(s).

2020-06-10 10:34 UTC, marcellinodour commented
Review ok
Warning sur méthode createTeacher, prévu d'être résolu dans une prochaine tâche

2020-06-11 08:52 UTC, oliviercailloux requested changes
SEP SVP.
L’explication fournie dans cette PR est utile, il faut la transférer dans votre doc.
Merci de me fournir un lien vers un diagramme qui me permet de suivre vos explications et de comprendre votre intention.

2020-06-12 14:40 UTC, TajouriSarra commented
Voici le diagramme qui schématise l'organisation de la bdd Rof de Dauphine. https://github.com/marcellinodour/MIDO-SVG/blob/master/Doc/Diagrams/ROFDauphineClassDiagram.svg

2020-06-15 17:11 UTC, oliviercailloux requested changes
La description de cette PR et son titre semblent annoncer un changement léger (ajout d’une méthode pour obtenir des informations de ROF ?). Mais je vois 20 fichiers changés, dont semble-t-il des changements déjà approuvés par ailleurs. Et un conflit est à résoudre.

2020-06-19 11:43 UTC, closed without merging