DEV BDD IT3 : Add class ROFDATABASE + JU
marcellinodour/MIDO-SVG pull request #28
Opened 2020-06-19 11:46 UTC by marcellinodour

La récupération du département s’est faite sur deux étapes:

Ajout des classes getOrgUnit et getOrgUnits dans Querier
à partir de la clé correspondant au département MIDO dans refRof/root/OrgUnit on récupère le département
La récupération des formations ne pouvait se faire en cascade à partir du département. En effet, comme renseigné dans le diagramme de classe ROFDataBase, il n’existe pas de lien entre OrgUnit et Programs ou Mentions. Par conséquent, nous avons cherché les clés correspondant aux formations MIDO dans Rof et que nous avons utilisé ensuite pour récupérer les Mentions et convertir en Licence ou Master selon le niveau d’étude. Il existe d’ailleurs des doublons qu’il faut gérer.

La récupération des cours s’est faite à partir des programmes. En effet, chaque program pointe vers une liste de program (dans refProgram) et chaque Program dans cette liste pointe vers une autre liste de Program et ainsi de suite. Quand on arrive aux niveaux les plus fins refProgram est vide et refCourse contient tous les cours correspondant aux Program(s) père(s).

WARNING : WORKFLOW non fonctionnel car refROF indisponible, l'action sera relancé vers 14h

2020-06-19 15:21 UTC, oliviercailloux requested changes
Ceci remplace-t-il la PR dont nous avons parlé ? Pouvez-vous la lier en commentaire ? Pouvez-vous m’indiquer un lien vers un ou plusieurs diagrammes qui me permettent de comprendre vos explications ?  Re-demandez une review SVP quand RefROF est disponible et que les tests passent (ou dites-moi s’il reste indisponible longtemps ou qu’il y a un autre problème).

2020-06-19 15:54 UTC, TajouriSarra commented
Oui ceci remplace la PR #27 
Voici un lien vers une documentation (toujours en cours de rédaction pour l'it 5 UML) https://github.com/marcellinodour/MIDO-SVG/blob/master/Doc/ROFDauphineDoc.adoc 
Pour les tests je crains qu'ils passeront pas, étant donné le problème des Mentions qui ont disparu dans testapi (comme discuté il y a quelques jours). Je tiens à préciser que tous les tests passaient avant cet incident.

2020-06-20 21:59 UTC, oliviercailloux requested changes
D’après GH WF, Maven échoue à récupérer le WSDL. Ceci semble différer de l’absence de mentions. Par ailleurs, pouvez-vous modifier les tests facilement pour les faire utiliser d’autres mentions ? Ou indiquez-moi SVP quels problèmes cela poserait.

2020-06-21 14:01 UTC, marcellinodour commented
Monsieur,
Pour le GH WF, la récupération WSDL a échoué de votre côté car vous il a été run à une heure de "fermeture REFROF" (de souvenir la base n'est plus accessible après 22h et entre 12h-14h).

Pour la suite, après échange avec @TajouriSarra nous nous sommes rendu compte d'une autre problème sous-jacent. Récemment, il semblerait que la base REFROF a fait l'objet d'une maintenance rendant ainsi nos test obsolètes. Il s'avère que les tests initialement programmé concernait un cas bien précis. Cas malheureusement inéxsistant à ce jour. A la vue du temps et du retard déjà entreprit pour cette tâche, nous nous sommes permis de désactiver ces tests. Une évolution est donc à prévoir dans l'it 4 Java. Qu'en pensez-vous ?

2020-06-21 14:16 UTC, TajouriSarra commented
Monsieur, 
Pour compléter le commentaire de Marcellino, j'ai essayé de modifier les tests pour utiliser des mentions présentes dans testapi à ce jour. Cependant je me rends compte d'un autre problème qui n'existait pas auparavant. La récupération des noms de Program et Course n'est plus fonctionnelle, bien que celle de ects, programId, courseId... se fait normalement. Ce problème est peut être dû à la présence de deux champs (fr et en) dans courseName et programName bien que cela ne posait aucun problème il y a quelques jours. Il faut bien creuser pour régler ce problème et donc je me dis qu'il est peut être plus judicieux de le faire à l'it4 java. Je rejoins donc Marcellino sur la demande de désactiver les tests.

2020-06-22 11:32 UTC, oliviercailloux requested changes
Ok pour postposer le rétablissement des tests unitaires. Je vous invite à laisser les tests tels quels, pour qu’on voie qu’ils échouent et qu’on voie le problème.

Il semble, toujours d’après GH WF, que Maven échoue à cause d’un problème de compilation et non pas à cause de tests unitaires. Voudriez-vous investiguer ?

2020-06-22 20:22 UTC, TajouriSarra commented
Oui, Maven échoue à cause de 9 erreurs de compilation de ce type ==> "incompatible types: CourseName cannot be converted to java.lang.String " (à l'origine de l'échec de la récupération des courseName, programName...)
Il semblerait que la méthode getValue() qui permettait de récupérer la valeur de la donnée des champs JAXBElement ne remplisse plus sa fonction.
Investigation en cours ...

2020-06-23 12:17 UTC, oliviercailloux requested changes

2020-06-23 12:17 UTC, oliviercailloux commented on src/test/java/com/github/cocolollipop/mido_svg/database/RofDatabaseTest.java
> +	void testSubjectsMIAGEApp() throws Exception {
Ce test est très fragile. Si on change le programme légèrement, ne fût-ce qu’un mot dans l’intitulé d’un cours (ce qui arrive), il échouera. Mieux vaudrait tester un peu moins précisément. Par exemple : vérifier qu’un cours contient le terme Java ; un ou deux autres, le terme Anglais ; vérifier qu’il y a entre 10 et 30 cours…

2020-06-23 12:17 UTC, oliviercailloux commented on src/test/java/com/github/cocolollipop/mido_svg/database/RofDatabaseTest.java
> +		assertTrue(expected.isEmpty());
Il aurait été nettement plus clair de tester simplement l’égalité entre les deux ensembles de cours.

2020-06-23 12:17 UTC, oliviercailloux commented on src/main/java/com/github/cocolollipop/mido_svg/database/RofDatabase.java
> +	private ImmutableList<Formation> formations;
Il me semble qu’un ensemble, plutôt qu’une liste, serait plus adéquat. (Même chose pour les tags.)

2020-06-23 12:17 UTC, oliviercailloux commented on src/main/java/com/github/cocolollipop/mido_svg/database/RofDatabase.java
> +				teacherList.put(subject.getResponsible().getLastName(),subject.getResponsible());
Comme discuté, teachers n’est pas ce qu’il vous faut, il me semble. FUTURE.

2020-06-23 12:17 UTC, oliviercailloux commented on src/main/java/com/github/cocolollipop/mido_svg/database/RofDatabase.java
> +	private List<Program> childProgram (Program program) throws StandardException{
Cf. BP FORMAT, SVP.

2020-06-23 12:17 UTC, oliviercailloux commented on src/main/java/com/github/cocolollipop/mido_svg/database/RofDatabase.java
> +				} catch (Exception e) {
Éviter un catch aussi général, si possible.

2020-06-23 12:22 UTC, oliviercailloux commented
Notez qu’un problème de compilation ne peut pas être dû à un problème à l’exécution (donc le problème rencontré par Maven ne peut pas être dû à un problème lors de l’exécution de getValue).

2020-06-23 12:25 UTC, oliviercailloux requested changes

2020-06-23 12:25 UTC, oliviercailloux commented on src/main/java/com/github/cocolollipop/mido_svg/university/components/Department.java
> +	public Department(String name) {
Appliquez SVP BP Local design factory methods.

2020-06-23 12:29 UTC, oliviercailloux commented
Plusieurs problèmes relevés ici semblent en fait liés à la PR #25.

2020-06-28 12:00 UTC, brulej commented
l'it3 est cloturée

2020-06-28 12:00 UTC, closed without merging