Dev svg it4bis
marcellinodour/MIDO-SVG pull request #32
Opened 2020-06-27 09:09 UTC by brulej

Cette PR reprend la PR #26 en prenant en compte les commentaires que vous y avez indiqué. Cependant, nous n'avons pas compris ce que vous attendiez concernant les BP null à appliquer dans la méthode countMaxSubjects de la classe ResponsiveSVG. Après relecture des BP, nous ne comprenons pas où se situe le problème dans notre méthode.

2020-06-27 19:17 UTC, brulej commented
La raison de l’échec du build a été identifiée, elle est due à un test qui n'est plus pertinent. Je vais donc supprimer la classe GUIJUnitTest qui avait été implémentée par les créateurs du projet.

2020-06-28 09:12 UTC, oliviercailloux approved these changes

2020-06-28 09:12 UTC, oliviercailloux commented on src/main/java/com/github/cocolollipop/mido_svg/svg_generator/DrawerSVGGen.java
> +	protected final static int heightOfRectangle = 25;
Conventions de nommage SVP.

Private ou Public.

2020-06-28 09:12 UTC, oliviercailloux commented on src/main/java/com/github/cocolollipop/mido_svg/svg_generator/ResponsiveSVG.java
> +	public Integer countMaxSubjects(Collection<Formation> list, int myYear) {
Il faut renvoyer `int`, puisqu’on ne veut pas pouvoir renvoyer `null`.

2020-06-28 09:13 UTC, oliviercailloux requested changes
Correction : en attente que les tests passent.

2020-06-28 10:32 UTC, brulej commented
> Correction : en attente que les tests passent.

compilation OK. J'ai opté pour une solution radicale, supprimer le test. En effet, il avait pour but de compter  les formations de la base fictive.

2020-06-28 11:42 UTC, camillelanglois3 commented on src/main/java/com/github/cocolollipop/mido_svg/svg_generator/DrawerSVGGen.java
> +	protected final static int heightOfRectangle = 25;
Corrections effectuées.

2020-06-28 11:42 UTC, camillelanglois3 commented on src/main/java/com/github/cocolollipop/mido_svg/svg_generator/ResponsiveSVG.java
> +	public Integer countMaxSubjects(Collection<Formation> list, int myYear) {
Correction effectuée

2020-06-28 11:43 UTC, camillelanglois3 commented
Pouvons-nous merge à présent ?

2020-06-28 13:53 UTC, oliviercailloux approved these changes
Ce test me semblait néanmoins marginalement utile, ne fût-ce qu’à des fins de documentation. Ne pouvez-vous pas le restituer en modifiant l’assertion ou ce que vous comptez ? Je vous laisse décider de la meilleure option puis fusionner.

2020-06-28 15:06 UTC, brulej commented
> Ce test me semblait néanmoins marginalement utile, ne fût-ce qu’à des fins de documentation. Ne pouvez-vous pas le restituer en modifiant l’assertion ou ce que vous comptez ? Je vous laisse décider de la meilleure option puis fusionner.

Le test ne marchait plus à cause de la méthode _countFormations_ , le deuxième paramètre n'était plus du bon type. J'ai simplement changé "M1" en 4.

2020-06-28 15:52 UTC, merged